
baseURL = "https://stayhometakeaction.netlify.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "🏡 Stay Home, Take Action ✨"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99.0

[params]
description = "Fight for whatever is the opposite of disaster capitalism from inside your home."
homeMetaContent = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
dateFormat = "Jan 2, 2006"
codePenUser = "someUser"
katex = true

[menu]

  [[menu.nav]]
  name = "💪Response Campaigns"
  url = "/response-campaigns"
  weight = 1.0

  [[menu.nav]]
  name = "🌈Resource Guides"
  url = "/resource-guides"
  weight = 2.0

  [[menu.nav]]
  name = "📚Readings"
  url = "/readings"
  weight = 3.0

  [[menu.nav]]
  name = "👀About"
  url = "/about/"
  weight = 4.0

[markup]
defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

  [markup.highlight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1.0
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4.0

  [markup.tableOfContents]
  endLevel = 6.0
  startLevel = 2.0